### PR TITLE
Character definitions

### PR DESCRIPTION
**Pull request by Malacath-92**
Not gonna add this to the Lua API until we merge #90

### CODE REVIEW

**Review by gmjosack — APPROVED** [review]
This looks good to me though `set_heart_color` might be fun for lua to make dynamic hearts

**Comment by Malacath-92** [comment]
Ah right, `set_heart_color` is actually the one that I wanted to expose. Not so much the name and gender stuff because that just seems wrong. But I'll take all y'all's lead on that  :)

**Comment by Dregu** [comment]
I'm not sure lowercase f should be a reserved global in lua, seems kinda common... I liked F more.

**Comment by Malacath-92** [comment]
Heh, that doesn't really matter to me. Just went with that python format strings would look like. I'll fix it later. If that's your only problem I'm even ready to merge.

**Comment by Dregu** [comment]
I think that's all! I wasn't sure you could actually make Colors first, but turns out Color.new() is a thing!

**Comment by Malacath-92** [comment]
All set now, added also `game_allocator` which might come in handy eventually, but for now it just avoids the crash in Debug when closing the game.

**Pull request merged**
