### PR TITLE
Add TeleporterBackpack (aka Telepack)

### PR DESCRIPTION
**Pull request by mauvealerts**
I assume this is the same size as the Teleporter field

### CODE REVIEW

**Comment by Dregu** [comment]
Oh yeah you need to add a few things to https://github.com/spelunky-fyi/overlunky/blob/main/src/game_api/script/usertypes/entities_items_lua.cpp#L107 to expose the usertype to lua.

**Comment by Mr-Auto** [comment]
and https://github.com/spelunky-fyi/overlunky/blob/main/src/game_api/script/usertypes/entity_casting_lua.cpp so get_entity will return proper type

**Comment by Malacath-92** [comment]
That entity casting stuff is auto generated. We should probably refrain from manually changing it and instead add the type to the x64dbg plugin.

**Comment by mauvealerts** [comment]
I think I've done everything. Let me know if there's more

**Pull request merged**
