### PR TITLE
Add basic settings API

### PR DESCRIPTION
**Pull request by Malacath-92**

### CODE REVIEW

**Comment by Dregu** [comment]
Oh right, `DAMSEL` is not used anywhere in the api or ui (except the sound guy didn't get the message), lets not call the setting damsel either.

**Comment by Malacath-92** [comment]
These enum values are generated from the binary, they are called like that internally. Do we really want to fiddle with that?

**Comment by Malacath-92** [comment]
Also what's the reference with "except the sound guy didn't get the message" exactly?

**Comment by Dregu** [comment]
In entities and textures they are called pets, but in sounds they are damsels.. There's even one for petting a damsel, which is pretty funny. I didn't know there were any other internal references to damsel.

**Pull request merged**
