### PR TITLE
fix MSVC 19.40 build crashing, fix clangd warnings

### PR DESCRIPTION
**Pull request by estebanfer**
Fixed latest MSVC build crashing when it injects to spelunky (the MSVC version now used for playlunky autobuild)
Fixed warning [-Wdeprecated-this-capture](https://www.emmtrix.com/wiki/Clang:Diag/warn_deprecated_this_capture)

### CODE REVIEW

**Comment by estebanfer** [comment]
Updating clang to the version used gives me errors completely unrelated to the one in CI :/

**Comment by Mr-Auto** [comment]
> Updating clang to the version used gives me errors completely unrelated to the one in CI :/

Typical at this point

**Comment by estebanfer** [comment]
Seems like clang made an oopsie in clang 18 and we'll have to wait til the new release that fixes it is out for the CI
https://github.com/ThePhD/sol2/issues/1581

**Comment by estebanfer** [comment]
how do I retry the CI? the new clang version is out

**Comment by Mr-Auto** [comment]
> how do I retry the CI? the new clang version is out

Only mentainors can, but if you want to just try, why not make PR inside your fork?

**Comment by estebanfer** [comment]
oops now I broke the CI

**Comment by estebanfer** [comment]
should I also downgrade MSVC 14.39 like in Playlunky or is this fine

**Comment by Dregu** [comment]
Woah, green!

> should I also downgrade MSVC 14.39 like in Playlunky or is this fine

I guess it doesn't matter as long as this code builds and works on both versions?

**Comment by estebanfer** [comment]
Playlunky didn't seem to work on 14.40 by applying this same fix of `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR`, while OL did work. Maybe could be somehow fixed in PL but I couldn't figure out how, I still got the mutex crashes

**Comment by estebanfer** [comment]
Ideally the clang downgrade step would be removed once it gets updated with the bugfixes, if it compiles after that

**Comment by Dregu** [comment]
I guess I should merge this then and we'll see what it takes to get https://github.com/spelunky-fyi/Playlunky/pull/53 building next.

**Pull request merged**
